### ISSUE TITLE
V1.0 Road map

### ISSUE THREAD

**Issue by DhruvaSambrani** [IISERM/BooksApp#1]
These are the things we need to implement
- [x] Books List with search
- [x] Bundles list with search
- [ ] Book links in db
- [ ] Book links in frontend
- [ ] Book view
- [ ] Books download
- [ ] Bundles download
- [ ] downloaded books frontend
- [ ] add edit delete book entries
- [ ] help frontend
- [ ] how to deploy?

For any feature you wanna implement, comment here, I'll explain what needs to be done.

**Comment by aabhasgulati** [comment]
Books download and Bundles download + add delete book entries

**Comment by DhruvaSambrani** [comment]
Ok, so let's do Books download first
Overload Base.download(::Book) in app/resources/books/Books.jl

Assume that a Book has a link, as book.link, and use the download function to download the file and save it with the name of the book
